workflows:
  react-pwa-apk-build:
    name: React PWA to APK Build
    max_build_duration: 15
    instance_type: linux
    environment:
      node: 18
      npm: 8
    scripts:
      - name: Install global tools
        script: |
          npm install -g cordova @ionic/cli
          
      - name: Verify project structure
        script: |
          pwd
          ls -la
          ls -la frontend/
          
      - name: Install frontend dependencies
        script: |
          cd frontend
          npm ci
          
      - name: Build React PWA
        script: |
          cd frontend
          npm run build
          
      - name: Create Cordova project
        script: |
          cordova create myapp com.ai.pwa "AI Auto Fix PWA"
          
      - name: Copy PWA to Cordova
        script: |
          rm -rf myapp/www/*
          cp -r frontend/build/* myapp/www/
          
      - name: Add Android platform
        script: |
          cd myapp
          cordova platform add android@12
          
      - name: Build APK
        script: |
          cd myapp
          cordova build android --release
          
    artifacts:
      - myapp/platforms/android/app/build/outputs/apk/release/*.apk